### ISSUE TITLE
Are satellite retrievals being archived by LAR?

### ISSUE THREAD

**Issue by vonw** [wsular/airpact#10]
This is an Ongoing Task for NW-AIRQUEST.

1) What satellite retrievals are being archived?

2) What scripts are being used to acquire these data? We need to provide documentation for this and push it to GitHub.

3) Are there other satellite retrievals (newer ones from HAQAST??) that might be useful to acquire regularly?

**Comment by farrenthorpe** [comment]
Satellite data is not archived.  Satellite images are created and uploaded to the web server.  Perhaps the images are being archived.   The logs directory has too many files.  My personal opinion is that the methods and application of satellite data is defunct and should be redone as a new project.  Here is the crontab script that runs daily:  
00    17 *   *     *     ~airpact5/AIRHOME/run_ap5_day1/satellite/run_geoss_noarg.csh         > ~airpact5/AIRHOME/run_ap5_day1/satellite/logs/crontab_geoss_20
"`date +\%y\%m\%d\%H`".log
