### ISSUE TITLE
Remove Alcoa Intalco and Boardman power plant from AIRPACT5

### ISSUE THREAD

**Issue by vonw** [wsular/airpact#4]
Email from 13 December 2021 that explain this change:

Hi Farren,
 
            We agree that the Boardman power plant should be removed from the inventory for AIRPACT5.  Thanks.
 
Phil
 
Philip Allen
Air Qualtiy Division - Oregon DEQ
Portland, OR 97232
503-229-6904 (w)
503-970-0529 (cell)
philip.allen@state.or.us
 
 
 
From: Thorpe, Farren (ECY) <fher461@ECY.WA.GOV> 
Sent: Monday, December 13, 2021 1:35 PM
To: Walden, Von P. <v.walden@wsu.edu>
Cc: ALLEN Philip * DEQ <philip.allen@deq.state.or.us>
Subject: AIRPACT5 Update
 
Hi Von,
 
Jill Schulte requested that we turn off Alcoa Intalco and Boardman power plant in AIRPACT5 (they both shutdown last year).  If it’s OK with you, I’ll remove these two point sources from the AIRPACT5 EI at the end of the month, so starting Jan 1 2022 they will not be represented in the forecast.   I’m copying Phil in case Oregon has feelings on this.
 
- Farren L. Thorpe
Modeling & Emissions Inventory Scientist
WA Dept. of Ecology - Air Quality Program
P: (360) 407-7658     M: (360) 489-5575

**Comment by farrenthorpe** [comment]
Intalco and Boardman were both removed from the point EI (2017 NEI Update).  New filenames were created and the point.lst file was modified accordingly.  First forecast without these 2 facilities is 12/30/2021
